Flow Layout Container implementation
microsoft/Teams-AdaptiveCards-Mobile pull request #219
Opened 2024-08-23 09:37 UTC by singhmanp0707

# Related Issue

A Pull Request should close a **single** issue; multiple issues can be closed when the issues are **small and related**, but that should be an exception not the rule. Please keep Pull Requests small and targeted; large 'code drops' with dozens of files will be closed and asked to split into reviewable pieces. Reviews that need to be large due to dependencies will be
reviewed on a case-by-case basis.

Please use one of the well-known [github fixes keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to reference
the issue fixed with this PR (eg Fixes #<github issue number>). If an issue doesn't yet exist please create one to aid
in issue tracking.

**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a comma-delimited list per the reference
page above.

# Description

For all Pull Requests, please describe how the issue was fixed or how the feature was implemented from a summary level. This information will be used to help provide context to the reviewers of the pull request and should be additive to the issue being closed.

# Sample Card

If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card or a card added with this PR.

# How Verified

How you verified the fix, including one or all of the following:
1. New unit tests that were added if any. If none were added please add a quick line explaining why not.
2. Existing relevant unit/regression tests that you ran
3. Manual scenario verification if any; ***Do include .gif's or screenshots of the testing you performed here if you think that it
will aid in code reviews or corresponding fixes on other platforms for eg.***

2024-08-26 17:20 UTC, ardlank approved these changes

2024-08-27 10:17 UTC, wyAbhishek approved these changes

2024-08-28 10:42 UTC, prpatwa requested changes

2024-08-28 12:11 UTC, singhmanp0707 commented on source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/CompoundButtonRenderer.java
> -    private int dpToPx(Context context, int dp) {
done

2024-08-28 12:11 UTC, singhmanp0707 commented on source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java
> +    public static boolean isFlowLayoutEnabled() {
moved to a new file.

2024-08-28 12:22 UTC, singhmanp0707 commented on source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
> +        flexboxLayout.setAlignItems(AlignItems.FLEX_START);
AlignItems is the alignment of the items on the flex line across cross axis. The default value is FLEX_START. Yes, it needs to be FLEX_START always irrespective of the horizontal alignment. Horizontal alignment is done using justifyContent property.

2024-08-28 12:23 UTC, singhmanp0707 commented on source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
> +            flexboxLayout.setAlignItems(AlignItems.FLEX_START);
same as per earlier comment.
Removed the `flexboxLayout.setAlignItems(AlignItems.FLEX_START);` as the default value is this only.

2024-08-28 15:15 UTC, prpatwa approved these changes

2024-08-28 23:27 UTC, GabrielMedAlv commented
Is there some unit test could be added for this feature? If a card with nested layout could be added to ensure is working would be great.

2024-08-28 23:27 UTC, GabrielMedAlv approved these changes

2024-08-29 12:21 UTC, singhmanp0707 commented
> Is there some unit test could be added for this feature? If a card with nested layout could be added to ensure is working would be great.

The NestedFlowLayout example is already added in the samples.

2024-09-02 06:58 UTC, merged